title: Creek Service
description: >-
  Quickly build & test an ecosystem of JVM based microservices, 
  using Kafka clients, Kafka Streams and more.
url: "https://www.creekservice.org"
org_gituhub_url: "https://github.com/creek-service"
google_analytics: G-CZC5Z8YNH8

markdown: GFM
lsi: false
safe: true
remote_theme: pages-themes/slate@v0.2.0
highlighter: rouge
incremental: true
strict_front_matter: true
gist:
  noscript: false

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile*