lsi: false
safe: true
source: https://github.com/creek-service/creek-service.github.io
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-github-metadata
