title: Creek Service
description: >-
  Quickly build & test an ecosystem of JVM based microservices, 
  using Kafka clients, Kafka Streams and more.
url: "https://www.creekservice.org"
org_gituhub_url: "https://github.com/creek-service"

lsi: false
safe: true
remote_theme: pages-themes/slate@v0.2.0
highlighter: rouge
incremental: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile*